List<String> dogBreeds = [
  'Aidi',
  'Ainu Dog',
  'Airedale Terrier',
  'Akbash Dog',
  'Alano Español',
  'Alapaha Blue Blood Bulldog',
  'American Bully',
  'American Hairless Terrier',
  'American Leopard Hound',
  'American Mastiff',
  'American Staghound',
  'Andalusian Hound',
  'Anglo-Français de Petite Vénerie',
  'Ariégeois',
  'Armant',
  'Armenian Gampr dog',
  'Artois Hound',
  'Austrian Black and Tan Hound',
  'Austrian Pinscher',
  'Azawakh',
  'Bakharwal Dog',
  'Banjara Hound',
  'Barbet',
  'Basque Shepherd Dog',
  'Bavarian Mountain Hound',
  'Beagle-Harrier',
  'Belgian Laekenois',
  'Bergamasco Shepherd',
  'Berger Picard',
  'Biewer Terrier',
  'Billy',
  'Black Mouth Cur',
  'Bolognese',
  'Bosnian Coarse-haired Hound',
  'Bouvier des Ardennes',
  'Bracco Italiano',
  'Braque d\'Auvergne',
  'Braque du Bourbonnais',
  'Braque Francais',
  'Braque Saint-Germain',
  'Briquet Griffon Vendéen',
  'Bucovina Shepherd Dog',
  'Bull Arab',
  'Bulldog Campeiro',
  'Bully Kutta',
  'Burgos Pointer',
  'Cairn Terrier',
  'Canaan Dog',
  'Cane Corso',
  'Cardigan Welsh Corgi',
  'Carolina Dog',
  'Carpathian Shepherd Dog',
  'Catalan Sheepdog',
  'Ca de Bou',
  'Caucasian Shepherd Dog',
  'Cavapoo',
  'Central Asian Shepherd Dog',
  'Cesky Fousek',
  'Cesky Terrier',
  'Chesapeake Bay Retriever',
  'Chien Français Blanc et Noir',
  'Chien Français Blanc et Orange',
  'Chien Français Tricolore',
  'Chihuahua',
  'Chilean Terrier',
  'Chinook',
  'Chippiparai',
  'Chow Chow',
  'Cirneco dell\'Etna',
  'Clumber Spaniel',
  'Coban Kopegi',
  'Combai',
  'Cordoba Fighting Dog',
  'Coton de Tulear',
  'Cretan Hound',
  'Croatian Sheepdog',
  'Curly-Coated Retriever',
  'Cursinu',
  'Czechoslovakian Wolfdog',
  'Dachshund',
  'Dalmatian',
  'Dandie Dinmont Terrier',
  'Denmark Feist',
  'Deutsche Bracke',
  'Doberman Pinscher',
  'Dogo Cubano',
  'Dogo Guatemalteco',
  'Dogo Sardesco',
  'Drentse Patrijshond',
  'Drever',
  'Dunker',
  'Dutch Smoushond',
  'East Siberian Laika',
  'East-European Shepherd',
  'Ecuadorian Hairless Dog',
  'English Bulldog',
  'English Coonhound',
  'English Foxhound',
  'English Mastiff',
  'English Setter',
  'English Shepherd',
  'English Springer Spaniel',
  'English Toy Terrier',
  'Entlebucher Mountain Dog',
  'Estonian Hound',
  'Estrela Mountain Dog',
  'Eurasier',
  'Fell Terrier',
  'Fila Brasileiro',
  'Finnish Hound',
  'Finnish Lapphund',
  'Finnish Spitz',
  'Flat-Coated Retriever',
  'French Spaniel',
  'French Tricolour Hound',
  'Galgo Español',
  'Garafian Shepherd',
  'Gascon Saintongeois',
  'German Longhaired Pointer',
  'German Pinscher',
  'German Roughhaired Pointer',
  'German Spaniel',
  'Giant Schnauzer',
  'Glen of Imaal Terrier',
  'Golden Retriever',
  'Gordon Setter',
  'Grand Anglo-Français Blanc et Noir',
  'Grand Anglo-Français Blanc et Orange',
  'Grand Anglo-Français Tricolore',
  'Grand Basset Griffon Vendéen',
  'Grand Bleu de Gascogne',
  'Grand Gascon Saintongeois',
  'Greater Swiss Mountain Dog',
  'Greek Harehound',
  'Greenland Dog',
  'Greyhound',
  'Griffon Bleu de Gascogne',
  'Griffon Bruxellois',
  'Griffon Fauve de Bretagne',
  'Griffon Nivernais',
  'Gull Terrier',
  'Hällefors Elkhound',
  'Hamiltonstövare',
  'Hanover Hound',
  'Harlequin Pinscher',
  'Harrier',
  'Hawaiian Poi Dog',
  'Himalayan Sheepdog',
  'Hokkaido',
  'Hovawart',
  'Huntaway',
  'Hygen Hound',
  'Ibizan Hound',
  'Icelandic Sheepdog',
  'Indian Pariah Dog',
  'Indian Spitz',
  'Irish Red and White Setter',
  'Irish Setter',
  'Irish Terrier',
  'Irish Water Spaniel',
  'Irish Wolfhound',
  'Istrian Coarse-haired Hound',
  'Istrian Shorthaired Hound',
  'Italian Greyhound',
  'Jack Russell Terrier',
  'Japanese Chin',
  'Japanese Spitz',
  'Japanese Terrier',
  'Jindo',
  'Jonangi',
  'Kangal Shepherd Dog',
  'Kai Ken',
  'Kangal Shepherd Dog',
  'Karelian Bear Dog',
  'Kars',
  'Keeshond',
  'Kerry Beagle',
  'Kerry Blue Terrier',
  'King Charles Spaniel',
  'Kishu Ken',
  'Kleiner Münsterländer',
  'Kombai',
  'Kooikerhondje',
  'Koyun',
  'Kromfohrländer',
  'Kuchi',
  'Kumaon Mastiff',
  'Kuvasz',
  'Labradoodle',
  'Lagotto Romagnolo',
  'Lakeland Terrier',
  'Lancashire Heeler',
  'Landseer',
  'Lapponian Herder',
  'Large Münsterländer',
  'Leonberger',
  'Levriero Sardo',
  'Lhasa Apso',
  'Lithuanian Hound',
  'Löwchen',
  'Lupo Italiano',
  'Magyar Agár',
  'Mahratta Greyhound',
  'Majorca Shepherd Dog',
  'Malinois',
  'Maltese',
  'Manchester Terrier',
  'Maremma Sheepdog',
  'Mastiff',
  'McNab',
  'Miniature American Shepherd',
  'Miniature Australian Shepherd',
  'Miniature Bull Terrier',
  'Miniature Fox Terrier',
  'Miniature Pinscher',
  'Miniature Schnauzer',
  'Montenegrin Mountain Hound',
  'Moscow Watchdog',
  'Moscow Water Dog',
  'Mountain Cur',
  'Mucuchies',
  'Mudhol Hound',
  'Mudi',
  'Neapolitan Mastiff',
  'New Guinea Singing Dog',
  'New Zealand Heading Dog',
  'Newfoundland',
  'Norfolk Terrier',
  'Norrbottenspets',
  'Northern Inuit Dog',
  'Norwegian Buhund',
  'Norwegian Elkhound',
  'Norwegian Lundehund',
  'Norwich Terrier',
  'Nova Scotia Duck Tolling Retriever',
  'Old Croatian Sighthound',
  'Old Danish Pointer',
  'Old English Sheepdog',
  'Olde English Bulldogge',
  'Otterhound',
  'Pachon Navarro',
  'Paisley Terrier',
  'Papillon',
  'Parson Russell Terrier',
  'Patterdale Terrier',
  'Pekingese',
  'Pembroke Welsh Corgi',
  'Perro Majorero',
  'Peruvian Inca Orchid',
  'Petit Basset Griffon Vendéen',
  'Phalène',
  'Pharaoh Hound',
  'Phu Quoc Ridgeback',
  'Picardy Spaniel',
  'Plott Hound',
  'Podenco Canario',
  'Pointer',
  'Polish Greyhound',
  'Polish Hound',
  'Polish Hunting Dog',
  'Polish Lowland Sheepdog',
  'Polish Tatra Sheepdog',
  'Pomeranian',
  'Pont-Audemer Spaniel',
  'Poodle',
  'Porcelaine',
  'Portuguese Podengo',
  'Portuguese Pointer',
  'Portuguese Water Dog',
  'Posavac Hound',
  'Pražský Krysařík',
  'Pshdar dog',
  'Pudelpointer',
  'Pug',
  'Puli',
  'Pumi',
  'Pyrenean Mastiff',
  'Pyrenean Shepherd',
  'Rafeiro do Alentejo',
  'Rajapalayam',
  'Rampur Greyhound',
  'Rat Terrier',
  'Redbone Coonhound',
  'Rhodesian Ridgeback',
  'Rottweiler',
  'Russell Terrier',
  'Russian Spaniel',
  'Russian Toy',
  'Russo-European Laika',
  'Saarloos Wolfdog',
  'Sabueso Español',
  'Saint-Usuge Spaniel',
  'Saluki',
  'Samoyed',
  'Sapsali',
  'Schapendoes',
  'Schillerstövare',
  'Schipperke',
  'Scottish Deerhound',
  'Sealyham Terrier',
  'Segugio Italiano',
  'Serrano Bulldog',
  'Shetland Sheepdog',
  'Shiba Inu',
  'Shih Tzu',
  'Shikoku',
  'Siberian Husky',
  'Silken Windhound',
  'Silky Terrier',
  'Sinhala Hound',
  'Skye Terrier',
  'Sloughi',
  'Slovak Cuvac',
  'Slovakian Rough-haired Pointer',
  'Slovenský Kopov',
  'Small Greek Domestic Dog',
  'Small Münsterländer',
  'Smooth Collie',
  'Smooth Fox Terrier',
  'South Russian Ovcharka',
  'Spanish Mastiff',
  'Spanish Water Dog',
  'Spinone Italiano',
  'Sporting Lucas Terrier',
  'Stabyhoun',
  'Staffordshire Bull Terrier',
  'Stephens Stock',
  'St. Bernard',
  'Stumpy Tail Cattle Dog',
  'Sundanese Dog',
  'Sussex Spaniel',
  'Swedish Elkhound',
  'Swedish Lapphund',
  'Swedish Vallhund',
  'Taiwan Dog',
  'Tamaskan Dog',
  'Teddy Roosevelt Terrier',
  'Telomian',
  'Tenterfield Terrier',
  'Tibetan Kyi Apso',
  'Tibetan Mastiff',
  'Tibetan Spaniel',
  'Tibetan Terrier',
  'Tornjak',
  'Tosa',
  'Toy Bulldog',
  'Toy Fox Terrier',
  'Toy Manchester Terrier',
  'Toy Trawler Spaniel',
  'Transylvanian Hound',
  'Treeing Cur',
  'Treeing Walker Coonhound',
  'Trigg Hound',
  'Tyrolean Hound',
  'Villano de Las Encartaciones',
  'Vizsla',
  'Volpino Italiano',
  'Weimaraner',
  'Welsh Corgi',
  'Welsh Sheepdog',
  'Welsh Springer Spaniel',
  'Welsh Terrier',
  'West Country Harrier',
  'West Highland White Terrier',
  'West Siberian Laika',
  'Westphalian Dachsbracke',
  'Wetterhoun',
  'Whippet',
  'White Shepherd',
  'Wire Fox Terrier',
  'Wirehaired Pointing Griffon',
  'Wirehaired Vizsla',
  'Württemberg Cattle Dog',
  'Yakutian Laika',
  'Yorkshire Terrier',
];
List<String> catBreeds = [
  'Abyssinian',
  'Aegean',
  'American Bobtail',
  'American Curl',
  'American Shorthair',
  'American Wirehair',
  'Arabian Mau',
  'Asian Semi-longhair',
  'Australian Mist',
  'Balinese',
  'Bambino',
  'Bengal',
  'Birman',
  'Bombay',
  'Brazilian Shorthair',
  'British Longhair',
  'British Shorthair',
  'Burmese',
  'Burmilla',
  'California Spangled',
  'Chantilly-Tiffany',
  'Chartreux',
  'Chausie',
  'Cheetoh',
  'Colorpoint Shorthair',
  'Cornish Rex',
  'Cymric',
  'Cyprus',
  'Devon Rex',
  'Donskoy',
  'Dragon Li',
  'Dwelf',
  'Egyptian Mau',
  'European Shorthair',
  'Exotic Shorthair',
  'Foldex',
  'German Rex',
  'Havana Brown',
  'Highlander',
  'Himalayan',
  'Japanese Bobtail',
  'Javanese',
  'Kanaani',
  'Khao Manee',
  'Kinkalow',
  'Korat',
  'Korean Bobtail',
  'Korn Ja',
  'Kurilian Bobtail',
  'Lambkin',
  'LaPerm',
  'Lykoi',
  'Maine Coon',
  'Manx',
  'Mekong Bobtail',
  'Minskin',
  'Napoleon',
  'Nebelung',
  'Norwegian Forest Cat',
  'Ocicat',
  'Ojos Azules',
  'Oregon Rex',
  'Oriental Bicolor',
  'Oriental Longhair',
  'Oriental Shorthair',
  'Persian',
  'Peterbald',
  'Pixie-bob',
  'Raas',
  'Ragamuffin',
  'Ragdoll',
  'Russian Blue',
  'Russian White',
  'Sam Sawet',
  'Savannah',
  'Scottish Fold',
  'Selkirk Rex',
  'Serengeti',
  'Serrade Petit',
  'Siamese',
  'Siberian',
  'Singapura',
  'Snowshoe',
  'Sokoke',
  'Somali',
  'Sphynx',
  'Suphalak',
  'Thai',
  'Tonkinese',
  'Toyger',
  'Turkish Angora',
  'Turkish Van',
  'Ukrainian Levkoy',
  'York Chocolate',
];
List<String> birdBreeds = [
  'African Grey Parrot',
  'Amazon Parrot',
  'Budgerigar',
  'Canary',
  'Cockatiel',
  'Cockatoo',
  'Conure',
  'Eclectus Parrot',
  'Finch',
  'Lovebird',
  'Macaw',
  'Parakeet',
  'Parrotlet',
  'Pigeon',
  'Poicephalus Parrot',
  'Quaker Parrot',
];
List<String> rabbitBreeds = [
  'American Fuzzy Lop',
  'American Sable',
  'Angora',
  'Belgian Hare',
  'Beveren',
  'Blanc de Hotot',
  'Britannia Petite',
  'Californian',
  'Champagne D’Argent',
  'Checkered Giant',
  'Cinnamon',
  'Continental Giant',
  'Cream D’Argent',
  'Czech Red',
  'Dwarf Hotot',
  'Dutch',
  'English Angora',
  'English Lop',
  'English Spot',
  'Flemish Giant',
  'Florida White',
  'French Angora',
  'French Lop',
  'German Angora',
  'Giant Angora',
  'Giant Chinchilla',
  'Harlequin',
  'Havana',
  'Himalayan',
  'Holland Lop',
  'Jersey Wooly',
  'Lilac',
  'Lionhead',
  'Mini Lop',
  'Mini Rex',
  'Mini Satin',
  'Netherland Dwarf',
  'New Zealand',
  'Palomino',
  'Polish',
  'Rex',
  'Rhinelander',
  'Sable',
  'Satin',
  'Satin Angora',
  'Silver',
  'Silver Fox',
  'Silver Marten',
  'Tan',
  'Thrianta',
];
List<String> fishBreeds = [
  'Other',
  'Angelfish',
  'Betta Fish',
  'Catfish',
  'Clownfish',
  'Guppy',
  'Goldfish',
  'Neon Tetra',
  'Molly',
  'Zebrafish',
  'Discus',
  'Cichlid',
  'Tiger Barb',
  'Koi',
  'Oscar Fish',
  'Plecostomus',
  'Bristlenose Pleco',
  'Rainbowfish',
  'Gourami',
  'Tetra',
  'Danio',
  'Killifish',
  'Bala Shark',
  'Siamese Fighting Fish',
  'Paradise Fish',
  'Piranha',
  'Archerfish',
  'Pufferfish',
  'Axolotl',
  'Arowana',
  'Blue Tang',
  'Butterflyfish',
  'Cardinalfish',
  'Dwarf Gourami',
  'Firemouth Cichlid',
  'Green Terror',
  'Jack Dempsey',
  'Mandarinfish',
  'Pictus Catfish',
];

List<String> hamsterBreeds = [
  'Other',
  'Syrian Hamster',
  'Dwarf Campbell Russian Hamster',
  'Dwarf Winter White Russian Hamster',
  'Chinese Hamster',
  'Roborovski Hamster',
  'Teddy Bear Hamster',
  'Golden Hamster',
  'Panda Hamster',
  'European Hamster',
  'African Pygmy Hamster',
  'Long-haired Syrian Hamster',
  'Short-haired Syrian Hamster',
  'White Russian Hamster',
  'Campbell\'s Dwarf Hamster',
  'Winter White Dwarf Hamster',
  'Russian Dwarf Hamster',
  'Chinese Striped Hamster',
  'Chinese Dwarf Hamster',
  'Djungarian Hamster',
  'Campbell\'s Russian Hamster',
  'European Black-bellied Hamster',
  'European Hamster',
  'Grey Hamster',
  'Golden Hamster',
  'Jungar Hamster',
  'Kazakh Hamster',
  'Long-haired Hamster',
  'Mongolian Hamster',
  'Panda Hamster',
  'Romanov Hamster',
  'Steppe Hamster',
  'Striped Hamster',
  'Syrian Black Hamster',
  'Syrian Desert Hamster',
  'Syrian Hamster',
  'Syrian Wild Hamster',
  'White Hamster',
  'White Russian Hamster',
  'Winter White Hamster',
];

List<String> turtleBreeds = [
  'Other',
  'African Aquatic Sideneck Turtle',
  'African Helmeted Turtle',
  'Alligator Snapping Turtle',
  'Blanding\'s Turtle',
  'Box Turtle',
  'Caspian Pond Turtle',
  'Chicken Turtle',
  'Common Snapping Turtle',
  'Diamondback Terrapin',
  'Eastern Box Turtle',
  'Eastern Long-necked Turtle',
  'Eastern Snake-necked Turtle',
  'European Pond Turtle',
  'European Pond Terrapin',
  'Florida Red-bellied Cooter',
  'Gulf Coast Box Turtle',
  'Indian Roofed Turtle',
  'Indian Star Tortoise',
  'Indian Tent Turtle',
  'Keeled Box Turtle',
  'Leopard Tortoise',
  'Mata Mata Turtle',
  'Mississippi Map Turtle',
  'Musk Turtle',
  'Ornate Box Turtle',
  'Painted Turtle',
  'Pancake Tortoise',
  'Pig-nosed Turtle',
  'Pond Turtle',
  'Red-eared Slider',
  'Reeves\' Turtle',
  'Snapping Turtle',
  'Spiny Softshell Turtle',
  'Sri Lankan Star Tortoise',
  'Sulcata Tortoise',
  'Terrapin',
  'Three-toed Box Turtle',
  'Western Painted Turtle',
  'Wood Turtle',
];
