name: ploofypaws
description: 'A new Flutter project.'

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
    sdk: '>=3.3.3 <4.0.0'

dependencies:
    flutter:
        sdk: flutter

    cupertino_icons: ^1.0.8
    google_fonts: ^6.2.1
    modal_bottom_sheet: ^3.0.0
    flutter_native_splash: ^2.4.0
    shared_preferences: ^2.2.2
    flutter_riverpod: ^2.5.1
    dio: ^5.4.2+1
    firebase_core:
    cloud_firestore: ^5.0.1
    flutter_form_builder: ^9.2.1
    form_builder_validators: ^11.0.0
    freezed_annotation: ^2.4.1
    json_annotation: ^4.8.1
    iconsax: ^0.0.8
    get_it: ^7.6.7
    flutter_svg: ^2.0.10+1
    pin_code_fields: ^8.0.1
    google_sign_in: ^6.2.1
    shimmer: ^3.0.0
    lottie: ^3.1.0
    grouped_list: ^6.0.0
    pull_down_button: ^0.10.1
    intl: ^0.19.0
    file_picker: ^8.0.3
    mobile_scanner: ^5.1.1
    permission_handler: ^11.3.1
    image_picker: ^1.1.2
    device_info_plus: ^10.1.0
    razorpay_flutter: ^1.3.7
    table_calendar: ^3.1.1
    flutter_map: ^7.0.0
    latlong2: ^0.9.1
    location: ^7.0.0
    geolocator: ^12.0.0
    http: ^1.2.1
    carousel_slider: ^5.0.0
    videosdk: ^1.1.12
    provider: ^6.1.2
    firebase_auth: ^5.1.1
    delightful_toast: ^1.1.0
    google_generative_ai: ^0.4.3
    flutter_dotenv: ^5.1.0
    firebase_storage: ^12.1.1
    mapbox_maps_flutter: ^2.0.0
    url_launcher: ^6.3.0
    video_player: ^2.9.1
    cached_network_image: ^3.3.1
    path_provider: ^2.1.3
    sqflite: ^2.3.3+1
    flutter_launcher_icons: ^0.13.1
    hexcolor:
    animated_switch: ^0.0.3
    cupertino_battery_indicator: ^1.1.0
    flutter_swipe_button: ^2.1.3

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^4.0.0
    build_runner: ^2.4.9
    freezed: ^2.4.7
    json_serializable: ^6.7.1

flutter:
    uses-material-design: true

    # To add assets to your application, add an assets section, like this:
    assets:
        - assets/app_icon/
        # - assets/images/
        - assets/images/content/
        # - assets/images/auth/
        # - assets/images/onboarding/
        # - assets/images/pet_onboarding/
        # - assets/images/placeholders/
        # - assets/images/services/
        - assets/lottie/
        - assets/svg/
        - assets/svg/dog1.svg
        - assets/svg/breakfastCard.png
        - assets/svg/emergency.png
        - assets/svg/prescription.png
        - assets/svg/best.png
        - assets/svg/proffesional.png
        - assets/svg/tele.png
        - assets/svg/health.png
        - assets/expert_consultations/

        # - assets/images/placeholders/user_avatar.png
        # - assets/images/content/fish_bowl_art.png
        # - assets/images/content/doctor_and_dog.png
        # - assets/images/content/puppy.jpeg
        # - assets/images/content/doodle_cat.png
        # - assets/images/content/dog_with_coat.jpeg
        # - assets/images/content/ai_bg.png
        - .env

    fonts:
        - family: Black-Mango
          fonts:
              - asset: assets/fonts/black-mango.ttf
